INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Kerala', 10, 3, 2, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 1, 2, 2, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 1, 1, 2, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 4, 0, 0, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 4, 0, 0, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 4, 3, 5, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 1, 1, 1, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Manali', 4, 2, 0, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 1, 2, 3, N'test1asdfg', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 4, 6, 9, N'test42zxcvb', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 5, 1, 1, N'test42zxcvb', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'', 0, 1, 1, N'', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'', 0, 1, 1, N'', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'', 0, 1, 1, N'', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 4, 3, 1, N'ishitashukla', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 5, 2, 2, N'akashakash123', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 3, 2, 1, N'arpangooner', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Kerala', 10, 2, 2, N'saileshindia', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 2, 1, 3, N'champadchampad', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Kerala', 10, 1, 4, N'champadchampad', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Jaipur', 2, 400, 2, N'', N'212752    ', N'11/25/2016 12:00:00 AM')
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 12, 1200, 1, N'', N'292710    ', N'11/11/2016 12:00:00 AM')
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'', 0, 1, 1, N'', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Shillong', 1, 1, 1, N'arpangooner', NULL, NULL)
INSERT INTO [dbo].[package] ([place_name], [number_of_days], [cost], [number_of_people], [customer_name], [transaction_id], [start_date]) VALUES (N'Manali', 1, 1, 1, N'arpangooner', NULL, NULL)
